services:
  abs-ranobedb:
    image: ghcr.io/kennethsible/abs-ranobedb
    container_name: abs-ranobedb
    environment:
      LOG_LEVEL: "INFO"
      SEARCH_LIMIT: 5
      PREFER_ROMAJI: "true"
    volumes:
      - ranobedb_cache:/app/cache
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  ranobedb_cache:
